---
- name: Copy php7.2
  copy:
    src: php7.2
    dest: /usr/local/bin/php7.2
    mode: a+x
  register: php72
  become: yes

- name: Alias php -> php7.2
  file:
    src: /usr/local/bin/php7.2
    dest: /usr/local/bin/php
    state: link
  register: php
  become: yes
  when: php72.changed

- name: Copy phpunit
  copy:
    src: phpunit
    dest: /usr/local/bin/phpunit
    mode: a+x
  register: phpunit
  become: yes

- name: Copy composer
  copy:
    src: composer
    dest: /usr/local/bin/composer
    mode: a+x
  register: composer
  become: yes

- name: Copy phpcs
  copy:
    src: phpcs
    dest: /usr/local/bin/phpcs
    mode: a+x
  register: phpcs
  become: yes

- name: Copy phpcbf
  copy:
    src: phpcbf
    dest: /usr/local/bin/phpcbf
    mode: a+x
  register: phpcbf
  become: yes

- name: Copy wp-cli
  copy:
    src: wp
    dest: /usr/local/bin/wp
    mode: a+x
  register: wp
  become: yes

- name: Copy wpscan
  copy:
    src: wpscan
    dest: /usr/local/bin/wpscan
    mode: a+x
  register: wpscan
  become: yes

- name: Copy phpdoc
  copy:
    src: phpdoc
    dest: /usr/local/bin/phpdoc
    mode: a+x
  register: phpdoc
  become: yes
