---
- name: Install libraries needed to make vim
  yum: name={{ item }} state=latest
  with_items:
    - gcc
    - gcc-c++
    - ncurses-devel
    - python-devel
    - cmake
  become: yes

- name: Clone vim
  git: repo=git://github.com/vim/vim.git
       dest=/tmp/vim
       version=v8.1.1343
  register: vim

- name: Make vim
  shell: "{{ item }}"
  args:
    chdir: /tmp/vim/src
  with_items:
    - ./configure --enable-pythoninterp
    - make
    - make install
  become: yes
  when: vim.changed

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc
  register: vimrc

- name: Install vim plugins
  shell: vim -c ":PlugInstall" -c q -c q -c q
  when: vimrc.changed

- name: alias vi to vim
  alternatives:
    name: vi
    link: /usr/local/bin/vi
    path: /usr/local/bin/vim
  become: yes

- name: Prepare ycm_build dir
  file:
    path: /tmp/ycm_build
    state: directory

- name: Compile the ycm_core library that YCM needs
  shell: "{{ item }}"
  args:
    chdir: /tmp/ycm_build
  with_items:
    - cmake -G "Unix Makefiles" . ~/.vim/plugged/YouCompleteMe/third_party/ycmd/cpp
    - cmake --build . --target ycm_core

